### ISSUE TITLE
[유미] 2022.07.28 TODO

### ISSUE THREAD

**Issue by ymStudyLog** [Wanted-Pre-Onboarding-FE-Team5/engall-class-schedule#1]
1. [x] Header, Background 포함된 Template 컴포넌트 layout 구현 
2. [x] 데이터가 뿌려질 안쪽 white box 구현 
3. [x] weekday tab 부분과 weekday 데이터가 들어갈 좁은 white box 구현

**Comment by ymStudyLog** [comment]
done
