### ISSUE TITLE
[유미] 2022.07.29 TODO

### ISSUE THREAD

**Issue by ymStudyLog** [Wanted-Pre-Onboarding-FE-Team5/engall-class-schedule#22]
1. [x] 전역처리한 scheduleState값 delete나 post로 db 변경시 다시 get하게 수정
2. [x] WeeklySchedule에서 시간순서대로 보여주기
3. [x] DailySchedule에서 startTime, endTime 데이터 가공
4. [x] 컨펌 팝업 스타일 수정

**Comment by ymStudyLog** [comment]
done
