### ISSUE TITLE
[유미] 2022.07.31 TODO

### ISSUE THREAD

**Issue by ymStudyLog** [Wanted-Pre-Onboarding-FE-Team5/engall-class-schedule#35]
1. [x] atom => 월요일 구하는 로직 수정
2. [x] AddSchedule 페이지에서 요일 선택시 토글 형식으로 => 여러번 누를 때 요일 데이터 중복 저장 방지
3. [x] hooks 삭제하고 WeeklySchedule 페이지에서 useEffect로 데이터 렌더링 처리

**Comment by ymStudyLog** [comment]
done
